version: "3.8"

services:
  app:
    image: "ghcr.io/remla25-team20/app:0.4.100"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - APP_VERSION=0.4.1
      - API_BASE_URL=http://model-service:8080

  model-service:
    image: "ghcr.io/remla25-team20/model-service:0.1.101"
    environment:
      - MODEL_SERVICE_VERSION=0.1.6
    volumes:
      - user-feedback-data-volume:/mnt/shared/user-feedback-data
      - models-volume:/mnt/shared/models/

volumes:
  user-feedback-data-volume:
  models-volume: