version: "3.8"

services:
  app:
    image: "ghcr.io/remla25-team20/app:0.1.latest"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0

  model-service:
    image: "ghcr.io/remla25-team20/model-service:latest"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOSTNAME=0.0.0.0
