version: '3.8'

services:
  app:
    build:
      context: ../app  # Adjust path if needed
      dockerfile: Dockerfile
      args:
        gh_token: ${GH_TOKEN}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
