# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-model-service-deployment"
  labels: { app: "{{ .Release.Name }}-model-service", version: "{{ .Values.modelService.version }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-model-service"
      version: "{{ .Values.modelService.version }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-model-service"
        version: "{{ .Values.modelService.version }}"
    spec:
      containers:
      - name: model-service
        image: ghcr.io/remla25-team20/model-service:{{  .Values.modelService.version  }}
        ports:
        - containerPort: {{ .Values.modelService.port }}
        env:
        - name: MODEL_SERVICE_VERSION
          value: "{{ .Values.modelService.version }}"
        volumeMounts:
            - name: user-feedback-data-volume
              mountPath: /mnt/shared/user-feedback-data
            - name: models-volume
              mountPath: /mnt/shared/models/
      volumes:
        - name: user-feedback-data-volume
          hostPath:
            path: "{{ .Values.modelService.userFeedbackData.hostPath }}"
            type: DirectoryOrCreate
        - name: models-volume
          hostPath:
            path: "{{ .Values.modelService.models.hostPath }}"
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-model-service-deployment-canary"
  labels: { app: "{{ .Release.Name }}-model-service", version: "{{ .Values.modelService.versionCanary }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-model-service"
      version: "{{ .Values.modelService.versionCanary }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-model-service"
        version: "{{ .Values.modelService.versionCanary }}"
    spec:
      containers:
      - name: model-service
        image: ghcr.io/remla25-team20/model-service:{{  .Values.modelService.versionCanary  }}
        ports:
        - containerPort: {{ .Values.modelService.port }}
        env:
        - name: MODEL_SERVICE_VERSION
          value: "{{ .Values.modelService.versionCanary }}"
        volumeMounts:
            - name: user-feedback-data-volume
              mountPath: /mnt/shared/user-feedback-data
            - name: models-volume
              mountPath: /mnt/shared/models/
      volumes:
        - name: user-feedback-data-volume
          hostPath:
            path: "{{ .Values.modelService.userFeedbackData.hostPath }}"
            type: DirectoryOrCreate
        - name: models-volume
          hostPath:
            path: "{{ .Values.modelService.models.hostPath }}"
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels: { app: "{{ .Release.Name }}", version: "{{ .Values.app.version }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      version: "{{ .Values.app.version }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        version: "{{ .Values.app.version }}"
    spec:
      containers:
      - name: app
        image: "ghcr.io/remla25-team20/app:{{ .Values.app.version  }}"
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: API_BASE_URL
          value: "http://{{ .Release.Name }}-{{ .Values.modelService.name  }}:{{  .Values.modelService.port  }}"
        - name: APP_VERSION
          value: "{{ .Values.app.version }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment-canary"
  labels: { app: "{{ .Release.Name }}", version: "{{ .Values.app.versionCanary }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      version: "{{ .Values.app.versionCanary }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        version: "{{ .Values.app.versionCanary }}"
    spec:
      containers:
      - name: app
        image: "ghcr.io/remla25-team20/app:{{ .Values.app.versionCanary  }}"
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: API_BASE_URL
          value: "http://{{ .Release.Name }}-{{ .Values.modelService.name  }}:{{  .Values.modelService.port  }}"
        - name: APP_VERSION
          value: "{{ .Values.app.versionCanary }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{  .Values.modelService.name  }}"
  labels:
    app: "{{ .Release.Name }}-model-service"  # so that the ServiceMonitor can find it
    app.kubernetes.io/managed-by: Helm # this was the default one
spec: 
  selector:
    app: "{{ .Release.Name }}-model-service"
  ports:
    - name: http  # For ServiceMonitor
      port: {{ .Values.modelService.port }}  # Use value from values.yaml
      targetPort: {{ .Values.modelService.port }}  # Keep consistent
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service-nginx"
spec:
  selector:
    app: "{{ .Release.Name }}"
    version: "{{ .Values.app.version }}"
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}-cert"
spec:
  secretName: "{{ .Release.Name }}-tls"
  dnsNames:
    - "{{ .Release.Name }}.local"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - "{{ .Release.Name }}.local"
      secretName: "{{ .Release.Name }}-tls"
  rules:
  - host: "{{ .Release.Name }}.local"
    http:
      paths:
      # front-end
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service-nginx"
            port:
              number: 3000

