# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment
  labels: { app: model-service, version: "{{ .Values.modelService.version }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-service
      version: "{{ .Values.modelService.version }}"
  template:
    metadata:
      labels:
        app: model-service
        version: "{{ .Values.modelService.version }}"
    spec:
      containers:
      - name: model-service
        image: ghcr.io/remla25-team20/model-service:{{  .Values.modelService.version  }}
        ports:
        - containerPort: {{ .Values.modelService.port }}
        env:
        - name: MODEL_SERVICE_VERSION
          value: "{{ .Values.modelService.version }}"
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-pat
              key: github-pat
        volumeMounts:
            - name: user-feedback-data-volume
              mountPath: /mnt/shared/user-feedback-data
            - name: models-volume
              mountPath: /mnt/shared/models/
      volumes:
        - name: user-feedback-data-volume
          hostPath:
            path: "{{ .Values.modelService.userFeedbackData.hostPath }}"
            type: DirectoryOrCreate
        - name: models-volume
          hostPath:
            path: "{{ .Values.modelService.models.hostPath }}"
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment-canary
  labels: { app: model-service, version: "{{ .Values.modelService.versionCanary }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-service
      version: "{{ .Values.modelService.versionCanary }}"
  template:
    metadata:
      labels:
        app: model-service
        version: "{{ .Values.modelService.versionCanary }}"
    spec:
      containers:
      - name: model-service
        image: ghcr.io/remla25-team20/model-service:{{  .Values.modelService.versionCanary  }}
        ports:
        - containerPort: {{ .Values.modelService.port }}
        env:
        - name: MODEL_SERVICE_VERSION
          value: "{{ .Values.modelService.versionCanary }}"
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-pat
              key: github-pat
        volumeMounts:
            - name: user-feedback-data-volume
              mountPath: /mnt/shared/user-feedback-data
            - name: models-volume
              mountPath: /mnt/shared/models/
      volumes:
        - name: user-feedback-data-volume
          hostPath:
            path: "{{ .Values.modelService.userFeedbackData.hostPath }}"
            type: DirectoryOrCreate
        - name: models-volume
          hostPath:
            path: "{{ .Values.modelService.models.hostPath }}"
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: { app: app, version: "{{ .Values.app.version }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
      version: "{{ .Values.app.version }}"
  template:
    metadata:
      labels:
        app: app
        version: "{{ .Values.app.version }}"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: app
        image: "ghcr.io/remla25-team20/app:{{ .Values.app.version  }}"
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: API_BASE_URL
          value: "http://{{ .Values.modelService.name  }}:{{  .Values.modelService.port  }}"
        - name: APP_VERSION
          value: "{{ .Values.app.version }}"
        volumeMounts:
        - name: models-volume
          mountPath: /mnt/shared/models/
      volumes:
        - name: models-volume
          hostPath:
            path: "{{ .Values.modelService.models.hostPath }}"
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-canary
  labels: { app: app, version: "{{ .Values.app.versionCanary }}" }
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
      version: "{{ .Values.app.versionCanary }}"
  template:
    metadata:
      labels:
        app: app
        version: "{{ .Values.app.versionCanary }}"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: app
        image: "ghcr.io/remla25-team20/app:{{ .Values.app.versionCanary  }}"
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: API_BASE_URL
          value: "http://{{ .Values.modelService.name  }}:{{  .Values.modelService.port  }}"
        - name: APP_VERSION
          value: "{{ .Values.app.versionCanary }}"
        volumeMounts:
        - name: models-volume
          mountPath: /mnt/shared/models/
      volumes:
        - name: models-volume
          hostPath:
            path: "{{ .Values.modelService.models.hostPath }}"
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.modelService.name  }}
  labels:
    app: model-service  # so that the ServiceMonitor can find it
    app.kubernetes.io/managed-by: Helm # this was the default one
spec: 
  selector:
    app: model-service
  ports:
    - name: http  # For ServiceMonitor
      port: {{ .Values.modelService.port }}  # Use value from values.yaml
      targetPort: {{ .Values.modelService.port }}  # Keep consistent
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
spec:
  secretName: app-tls
  dnsNames:
    - app.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - app.local
      secretName: app-tls
  rules:
  - host: app.local
    http:
      paths:
      # front-end
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 3000

