- hosts: all
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Copy metallb manifest to VM
      ansible.builtin.copy:
        src: resources/metallb-native.yaml
        dest: /tmp/metallb-native.yaml
    - name: Apply Flannel manifest
      ansible.builtin.command: kubectl apply -f /tmp/metallb-native.yaml
    - name: Wait until metallb is fully initialized
      ansible.builtin.command: >
        kubectl wait
        -n metallb-system
        -l app=metallb,component=controller --for=condition=ready
        pod
        --timeout=60s
    - name: Copy metallb resource definition manifest to VM
      ansible.builtin.copy:
        src: resources/metallb-resources.yaml
        dest: /tmp/metallb-resources.yaml
    - name: Initialize IPAddressPool and L2Advertisement
      ansible.builtin.command: kubectl apply -f /tmp/metallb-resources.yaml
    - name: Add Ingress-Nginx Helm repository
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"
    - name: Install Nginx Ingress Controller
      kubernetes.core.helm:
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        name: ingress-nginx
    - name: Add Kubernetes-dashboard Helm repository
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: "https://kubernetes.github.io/dashboard/"
    - name: Install Kubernetes Dashboard Controller
      kubernetes.core.helm:
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true
        name: kubernetes-dashboard
    - name: Copy adminuser manifest for dashboard
      ansible.builtin.copy:
        src: resources/dashboard-adminuser.yaml
        dest: /tmp/dashboard-adminuser.yaml
    - name: Apply adminuser manifest
      ansible.builtin.command: kubectl apply -f /tmp/dashboard-adminuser.yaml
    - name: Copy ingress manifest for dashboard
      ansible.builtin.copy:
        src: resources/dashboard-ingress.yaml
        dest: /tmp/dashboard-ingress.yaml
    - name: Apply Dashboard Ingress manifest
      ansible.builtin.command: kubectl apply -f /tmp/dashboard-ingress.yaml
