- hosts: all
  become: yes
  tasks:
    - name: Set authorized keys taken from keys folder
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: '{{ item }}'
      with_fileglob:
        - "/keys/*.pub"