- hosts: all
  become: yes

  vars:
    k8s_version: "1.32.4-1.1"

  tasks:
    - name: Set authorized keys taken from keys folder
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "host_keys/*.pub"
    - name: Disable SWAP
      ansible.builtin.shell: swapoff -a
    - name: Disable SWAP in fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/swap.*'
        state: absent
    - name: Automate module load at boot
      ansible.builtin.copy: 
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay
    - name: Load modules
      community.general.modprobe:
        name: "{{ item }}"
      loop:
        - br_netfilter
        - overlay
    - name: Enable IPv4 and IPv6 forwarding
      ansible.builtin.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        reload: yes
      with_items:
        - { name: 'net.ipv4.ip_forward', value: '1' }
        - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - name: Create /etc/hosts from template
      ansible.builtin.template:
        src: hosts_template.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
    - name: Add kubernetes GPG key
      ansible.builtin.apt_key:
        file: Release.key
        state: present
    - name: Add kubernetes repository
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/etc/apt/trusted.gpg] 
          https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
        filename: kubernetes
        state: present
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install K8s tools
      ansible.builtin.apt:
        name:
        - containerd=1.7.24-0ubuntu1~24.04.2
        - runc=1.1.12-0ubuntu3.1
        - kubelet={{ k8s_version }}
        - kubeadm={{ k8s_version }}
        - kubectl={{ k8s_version }}
