- hosts: all
  become: yes
  tasks:
    - name: Check if node is already joined
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf
    - name: Generate join command
      ansible.builtin.command: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_command
      when: not kubelet_conf.stat.exists
    - name: Join kubernetes cluster
      ansible.builtin.shell: "{{ join_command.stdout }}"
      when: not kubelet_conf.stat.exists